name: Twist_Solid_Test

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - pandas>=1.3.1
  - snakemake==7.16.0
  - singularity==3.8.5
  - jinja2==3.0.1
  - networkx
  - cyvcf2==0.30.16
  - tabulate<0.9.0
  - pip==21.3.1
  - pip:
    - hydra-genetics==0.15.0
