resources: "config/resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.1.8"

trimmer_software: "fastp_pe"

reference:
  background:  "/mnt/WD1/ref/Twist/PoN/26_normal_samples/background_panel_26_normal.tsv"
  artifacts: "/mnt/WD1/ref/Twist/PoN/26_normal_samples/artifact_panel_26_normal.tsv"
  fasta: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  dict: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.dict"
  amb: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  fai: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.fai"
  pac: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.sa"
  design_bed: "/mnt/WD1/ref/Twist/hydra_files/bed/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.reannotated.210608.bed"
  design_intervals: "/mnt/WD1/ref/Twist/hydra_files/bed/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.MUC6_31_rm.exon_only.reannotated.210608.interval_list"
  design_intervals_gatk_cnv: "/mnt/WD1/ref/Twist/hydra_files/bed/pool1_pool2_nochr_3c.sort.merged.padded20.cnv400.hg19.210311.met.annotated.bed.preprocessed.interval_list"
  fasta_rna: "/mnt/WD1/ref/Twist/Twist_RNA/GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa"
  design_bed_rna: "/mnt/WD1/ref/Twist/hydra_files/rna/bed/Twist_RNA_Design5.annotated.bed"
  design_intervals_rna: "/mnt/WD1/ref/Twist/hydra_files/rna/bed/Twist_RNA_Design5.annotated.interval_list"
  skip_chrs:
    - "chrM"

arriba:
  assembly: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.fasta"
  blacklist: "/mnt/WD1/ref/Twist/arriba/arriba_v2.3.0/database/blacklist_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"
  container: "docker://hydragenetics/arriba:2.3.0"
  gtf: "/mnt/WD1/ref/Twist/hydra_files/rna/hg19.refGene.gtf"
  extra: "-p /mnt/WD1/ref/Twist/arriba/arriba_v2.3.0/database/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3 -k /mnt/WD1/ref/Twist/arriba/arriba_v2.3.0/database/known_fusions_hg19_hs37d5_GRCh37_v2.3.0.tsv.gz"

arriba_draw_fusion:
  container: "docker://hydragenetics/arriba:2.3.0"
  cytobands: "/mnt/WD1/ref/Twist/arriba/arriba_v2.3.0/database/cytobands_hg19_hs37d5_GRCh37_v2.3.0.tsv"
  gtf: "/mnt/WD1/ref/Twist/hydra_files/rna/hg19.refGene.gtf"
  protein_domains: "/mnt/WD1/ref/Twist/arriba/arriba_v2.3.0/database/protein_domains_hg19_hs37d5_GRCh37_v2.3.0.gff3"

add_multi_snv_in_codon:
  af_limit: 0.00
  artifact_limit: 10000

annotate_cnv:
  cnv_amp_genes: "/mnt/WD1/ref/Twist/hydra_files/bed/cnv_amp_genes.bed"
  cnv_loh_genes: "/mnt/WD1/ref/Twist/hydra_files/bed/cnv_loh_genes.bed"
  # cnv_loh_genes: "/projects/wp1/nobackup/ngs/utveckling/Twist_DNA_DATA/bed/cnv_loh_genes.bed"

bcbio_variation_recall_ensemble:
  container: "docker://hydragenetics/bcbio-vc:0.2.6"
  callers:
    - vardict
    - gatk_mutect2

bcftools_filter_include_region:
  exon: "/mnt/WD1/ref/Twist/hydra_files/bed/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.MUC6_31_rm.exon_only.reannotated.210608.bed"

bcftools_id_snps:
  snps_bed: "/mnt/WD1/ref/Twist/hydra_files/rna/bed/ID_SNPs.bed"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  amb: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.amb"
  ann: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.ann"
  bwt: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.bwt"
  pac: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.pac"
  sa: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.sa"

bwa_mem_merge:
  extra: "-c"

cnvkit_batch:
  container: "docker://hydragenetics/cnvkit:0.9.9"
  normal_reference: "/mnt/WD1/ref/Twist/hydra_files/PoN/cnvkit_nextseq_36.cnn"
  method: "hybrid"

cnvkit_call:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnvkit_diagram:
  container: "docker://hydragenetics/cnvkit:0.9.9"

cnv_html_report:
  template: "config/cnv_report_template.html"

cnvkit_scatter:
  container: "docker://hydragenetics/cnvkit:0.9.9"

config_manta_t:
  container: "docker://hydragenetics/manta:1.6.0"
  extra: "--exome --callRegions /mnt/WD1/ref/Twist/hydra_files/bed/pool1_pool2.sort.merged.padded20.cnv200.hg19.split_fusion_genes.210608.bed.gz"

cnv_tsv_report:
  del_1p19q_cn_limit: 1.4
  del_1p19q_chr_arm_fraction: 0.3

exon_skipping:
  design_bed: "/mnt/WD1/ref/Twist/hydra_files/rna/bed/Twist_RNA_Design5.annotated.bed"

fastp_pe:
  container: "docker://hydragenetics/fastp:0.20.1"
  # Default enabled trimming parameters for fastp. Specified for clarity.
  extra: "--trim_poly_g --qualified_quality_phred 15 --unqualified_percent_limit 40 --n_base_limit 5 --length_required 15"

fastqc:
  container: "docker://hydragenetics/fastqc:0.11.9"

filter_vcf:
  snv_soft_filter: "config/config_soft_filter_uppsala.yaml"
  snv_hard_filter: "config/config_hard_filter_uppsala.yaml"
  cnv_hard_filter_amp: "config/config_hard_filter_cnv_amp.yaml"
  cnv_hard_filter_loh: "config/config_hard_filter_cnv_loh.yaml"
  germline: "config/config_hard_filter_germline.yaml"

fusioncatcher:
  container: "docker://hydragenetics/fusioncatcher:1.33"
  #container: "docker://hydragenetics/fusioncatcher:1.33"
  genome_path: "/mnt/WD1/ref/Twist/fusioncatcher/data/human_v102/"

gatk_calculate_contamination:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_cnv_call_copy_ratio_segments:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_cnv_collect_allelic_counts:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  SNP_interval: "/mnt/WD1/ref/Twist/hydra_files/bed/gnomad_SNP_0.001_target.annotated.interval_list"

gatk_cnv_collect_read_counts:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_cnv_denoise_read_counts:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  normal_reference: "/mnt/WD1/ref/Twist/hydra_files/PoN/gatk_cnv_nextseq_36.hdf5"

gatk_cnv_model_segments:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_get_pileup_summaries:
  container: "docker://hydragenetics/gatk4:4.1.9.0"
  sites: "/mnt/WD1/ref/Twist/hydra_files/contamination/small_exac_common_3.hg19.vcf.gz"
  variants: "/mnt/WD1/ref/Twist/hydra_files/contamination/small_exac_common_3.hg19.vcf.gz"

gatk_mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_mutect2_filter:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gatk_mutect2_merge_stats:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

gene_fuse:
  container: "docker://hydragenetics/genefuse:0.6.1"
  genes: "/mnt/WD1/ref/Twist/hydra_files/genefuse/GMS560_fusion_w_pool2.hg19.csv"
  fasta: "/mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/hg19.with.mt.fasta"

hotspot_annotation:
  hotspots: "/mnt/WD1/ref/Twist/hydra_files/bed/Hotspots_combined_regions_nodups.csv"
  chr_translation_file: "config/hotspot_report.chr.translation.hg19"

hotspot_info:
  hotspot_mutations: "/mnt/WD1/ref/Twist/hydra_files/bed/Hotspots_combined_regions_nodups.csv"

hotspot_report:
  hotspot_mutations: "/mnt/WD1/ref/Twist/hydra_files/bed/Hotspots_combined_regions_nodups.csv"
  report_config: "config/hotspot_report.yaml"
  chr_translation_file: "config/hotspot_report.chr.translation.hg19"
  levels:
    - [200, "ok", "yes"]
    - [30, "low", "yes"]
    - [0, "low", "not analyzable"]

manta_run_workflow_t:
  container: "docker://hydragenetics/manta:1.6.0"

mosdepth:
  container: "docker://hydragenetics/mosdepth:0.3.2"
  extra: "--no-per-base --fast-mode"

mosdepth_bed:
  container: "docker://hydragenetics/mosdepth:0.3.2"

msisensor_pro:
  container: "docker://hydragenetics/msisensor_pro:1.1.a"
  PoN: "/mnt/WD1/ref/Twist/hydra_files/PoN/Msisensor_pro_reference_nextseq_36.list_baseline"

multiqc:
  container: "docker://hydragenetics/multiqc:1.11"
  reports:
    DNA:
      config: "config/multiqc_config_dna.yaml"
      included_unit_types: ["N", "T"]
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
    RNA:
      config: "config/multiqc_config_rna.yaml"
      included_unit_types: ["R"]
      qc_files:
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip"
        - "qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip"
        - "qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt"
        - "qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt"
        - "qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt"
        - "qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt"
        - "qc/samtools_stats/{sample}_{type}.samtools-stats.txt"
        - "qc/mosdepth/{sample}_{type}.regions.bed.gz"

optitype:
  #container: "docker://hydragenetics/optitype:1.3.5"
  container: "docker://fred2/optitype"
  sample_type: "-d"
  enumeration: 4

picard_collect_alignment_summary_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_hs_metrics:
  container: "docker://hydragenetics/picard:2.25.0"
  extra: "COVERAGE_CAP=5000"

picard_collect_duplication_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_collect_insert_size_metrics:
  container: "docker://hydragenetics/picard:2.25.0"

picard_mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

report_fusions:
  annotation_bed: "/mnt/WD1/ref/Twist/hydra_files/rna/bed/Twist_RNA_fusionpartners.bed"
  fusioncather_flag_low_support: 15
  fusioncather_low_support: 3
  fusioncather_low_support_fp_genes: 20
  fusioncather_low_support_inframe: 6
  star_fusion_flag_low_support: 15
  star_fusion_low_support: 2
  star_fusion_low_support_fp_genes: 20
  star_fusion_low_support_inframe: 6

report_gene_fuse:
  filter_fusions: "/mnt/WD1/ref/Twist/hydra_files/genefuse/filter_fusions.csv"
  min_unique_reads: 6

samtools_merge_bam:
  extra: "-c"

scarhrd:
  container: "docker://hydragenetics/scarhrd:20200825"
  reference_name: "grch37"
  seqz: FALSE

star:
  container: "docker://hydragenetics/star:2.7.10a"
  # genome_index: "/data/ref_data/star/v2.7.10a_hg19/"
  # genome_index: "/mnt/WD1/ref/Twist/Twist_RNA/STAR_index_GRCh37_RefSeq_hg19"
  genome_index: /mnt/WD1/ref/Uppsala/Data/BWA_0.7.10_refseq/star_index
  extra: "--quantMode GeneCounts --sjdbGTFfile /mnt/WD1/ref/Twist/hydra_files/rna/hg19.refGene.gtf --outSAMtype BAM SortedByCoordinate --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --alignSJstitchMismatchNmax 5 -1 5 5 --chimSegmentReadGapMax 3"

star_fusion:
  container: "docker://hydragenetics/star-fusion:1.10.1"
  genome_path: "/mnt/WD1/ref/Twist/Twist_RNA/GRCh37_gencode_v19_CTAT_lib_Mar012021.plug-n-play/ctat_genome_lib_build_dir/"
  extra: "--examine_coding_effect"

svdb_merge:
  container: "docker://hydragenetics/svdb:2.6.0"
  cnv_callers:
    - "cnvkit"
    - "gatk_cnv"
  extra: "--pass_only" #Just merge the two vcf-files without merging regions

svdb_query:
  container: "docker://hydragenetics/svdb:2.6.0"
  db_string: "--db /mnt/WD1/ref/Twist/hydra_files/svdb/all_TN_292_svdb_0.8_20220505.vcf --out_frq Twist_AF --out_occ Twist_OCC"

tmb:
  filter_nr_observations: 1
  dp_limit: 100
  vd_limit: 10
  af_lower_limit: 0.05
  af_upper_limit: 0.45
  gnomad_limit: 0.0001
  db1000g_limit: 0.0001
  background_sd_limit: 5
  nssnv_tmb_correction: 1.02
  nssnv_ssnv_tmb_correction: 0.74

vardict:
  container: "docker://hydragenetics/vardict:1.8.3"
  bed_columns: "-c 1 -S 2 -E 3 -g 4"
  allele_frequency_threshold: "0.01"

vep:
  container: "docker://hydragenetics/vep:105"
  vep_cache:  "/mnt/WD1/ref/VEP/homo_sapiens_vep_105_GRCh37/"
  mode: --offline --cache
  extra: " --assembly GRCh37 --check_existing --pick --sift b --polyphen b --ccds --uniprot --hgvs --symbol --numbers --domains --regulatory --canonical --protein --biotype --uniprot --tsl --appris --gene_phenotype --af --af_1kg --af_gnomad --max_af --pubmed --variant_class "

vt_decompose:
  container: "docker://hydragenetics/vt:2015.11.10"

vt_normalize:
  container: "docker://hydragenetics/vt:2015.11.10"
